const Glyphs = {
    PLLus:require("../assets/images/+.png"),
    Add:require("../assets/images/add.png"),
    Arrow: require("../assets/images/Arrow.png"),
    Battery: require("../assets/images/Battery.png"),
    BlueButton: require("../assets/images/bluebutton.png"),
    Calender:require("../assets/images/Calender.png"),
    Contact: require("../assets/images/contact.png"),
    ContactForm:require("../assets/images/contact-form.png"),
    Customer: require("../assets/images/Customer.png"),
    Date: require("../assets/images/date.png"),
    Downward: require("../assets/images/Downward.png"),
    Edit:require("../assets/images/edit.png"),
    Editing:require("../assets/images/Editing.png"),
    Email: require("../assets/images/email.png"),
    Executed: require("../assets/images/Executed.png"),
    Eye: require("../assets/images/eye.png"),
    Eyecut:require("../assets/images/eyecut.png"),
    FaceScan: require("../assets/images/facescan.png"),
    Filter: require("../assets/images/filter.png"),
    FingerScan: require("../assets/images/fingerscan.png"),
    Frame:require("../assets/images/Frame.png"),
    Hands: require("../assets/images/Hands.png"),
    HandShake: require("../assets/images/Handshake.png"),
    Home: require("../assets/images/Home.png"),
    HomeDull: require("../assets/images/HomeDull.png"),
    Key: require("../assets/images/key.png"),
    Location: require("../assets/images/Location.png"),
    Mail: require("../assets/images/mail.png"),
    Mic: require("../assets/images/mic.png"),
    Mobile: require("../assets/images/Mobile.png"),
    Notification:require("../assets/images/notification.png"),
    Notify: require("../assets/images/Notify.png"),
    OrLine:require("../assets/images/orline.png"),
    Pending: require("../assets/images/pending.png"),
    Phone: require("../assets/images/phone.png"),
    Planned: require("../assets/images/Planned.png"),
    PlannedFrame: require("../assets/images/PlannedFrame.png"),
    Plus: require("../assets/images/plus.png"),
    Profile2User: require("../assets/images/profile2user.png"),
    Profile2UserClicked: require("../assets/images/profile2userClicked.png"),
    QR: require("../assets/images/QR.png"),
    Remember: require("../assets/images/remember.png"),
    Role: require("../assets/images/Role.png"),
    Rolled: require("../assets/images/rolled.png"),
    Sail: require("../assets/images/Sail.png"),
    SailLogo: require("../assets/images/SailLogo.png"),
    Search: require("../assets/images/search.png"),
    Setting2: require("../assets/images/setting2.png"),
    Setting2Clicked: require("../assets/images/setting2Clicked.png"),
    Shop: require("../assets/images/shop.png"),
    ShopClicked: require("../assets/images/shopClicked.png"),
    Splash: require("../assets/images/Splash.png"),
    StainLessSteel:require("../assets/images/StainlessSteel.png"),
    Steel: require("../assets/images/steel.png"),
    Visit: require("../assets/images/Visit.png"),
    Wifi: require("../assets/images/Wifi.png"),
  };
  export default Glyphs;